dist: focal
language: python
cache: pip

services:
  - postgresql

matrix:
  include:
   - env: TOXENV=py37-dj22-wamaster-postgres
     python: 3.7

   - env: TOXENV=py38-dj22-wamaster-postgres
     python: 3.8

   - env: TOXENV=py38-dj22-wamaster-sqlite
     python: 3.8

   - env: TOXENV=py37-dj30-wamaster-postgres
     python: 3.7

   - env: TOXENV=py38-dj30-wamaster-postgres
     python: 3.8

   - env: TOXENV=py38-dj31-wamaster-postgres
     python: 3.8

   - env: TOXENV=py38-dj31-wamaster-sqlite
     python: 3.8

# Not currently needed as we test against Wagtail master anyway
# When Wagtail 2.11 is released and the above environments are updated. Uncomment this.
#
#   - env: TOXENV=py38-dj31-wamaster-postgres
#     python: 3.8
#
#  allow_failures:
#   - env: TOXENV=py38-dj31-wamaster-postgres

install:
  - pip install tox

script:
  - tox
