name: Django React AppShell CI

on:
    push:

    pull_request:

jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Install dev dependencies
              run: |
                  python -m pip install .[dev]
            - name: Flake8
              run: flake8 .

    isort:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Install dev dependencies
              run: |
                  python -m pip install .[dev]
            - name: ISort
              run: isort --check .

    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Install dev dependencies
              run: |
                  python -m pip install .[dev]
            - name: Black
              run: black --check .

    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - name: Install prettier
              run: yarn install
            - name: Prettier
              run: ./node_modules/.bin/prettier --check .

    eslint-example:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - name: Install eslint
              run: cd example/client && yarn install
            - name: Eslint example
              run: cd example/client && ./node_modules/.bin/eslint
