name: Meze CI

on:
  push:

  pull_request:

jobs:
  lint_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dev dependencies
        run: |
          poetry install

      - name: Flake8
        run: |
          poetry run flake8

      - name: ISort
        run: |
          poetry run isort --check .

      - name: Black
        run: |
          poetry run black --check .

  lint_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          yarn install

      - name: Prettier
        run: |
          yarn run check-format

      - name: ESLint
        run: |
          yarn run lint

      - name: Tsc
        run: |
          cd packages/core
          yarn install
          yarn run check-types
