name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - uses: actions/checkout@v4

      - run: poetry install

      - name: Run ruff
        working-directory: .
        run: poetry run ruff check --output-format=github .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          npm install
      - run: |
          npm run check-format

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          npm install
      - run: |
          npm run lint

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          npm install
      - run: |
          cd packages/react
          npm install
          npm run check-types
